protocol = "acton-2150i"
doc = "Acton 2150i dual grating imaging monochromator."
traits = ["uses-uart", "has-turret", "has-limits", "has-position", "is-daemon"]
hardware = ["acton:2150i"]

[links]
documentation = "https://yaq.fyi/daemons/acton-2150i"
source = "https://github.com/yaq-project/yaqd-acton"
bugtracker = "https://github.com/yaq-project/yaqd-acton/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-acton/"
conda-forge = "https://anaconda.org/conda-forge/yaqd-acton"

[config.baud_rate]
default = 9600
